name: rio
version: 0.0.0.0

dependencies:
- base
- bytestring
- containers
- deepseq
- directory
- exceptions # FIXME what do we do with MonadThrow?
- filepath
- hashable
- microlens
- mtl
- text
- time
- typed-process >= 0.2.1.0
- unliftio
- unordered-containers
- vector

when:
- condition: os(windows)
  then:
    cpp-options: -DWINDOWS
    dependencies:
    - Win32
  else:
    dependencies:
    - unix

library:
  source-dirs: src/
  other-modules:
  - RIO.Prelude

  when:
  - condition: os(darwin)
    then:
      c-sources: cbits/time-osx.c
    else:
      when:
      - condition: os(windows)
        then:
          c-sources: cbits/time-windows.c
        else:
          c-sources: cbits/time-posix.c
