image: registry.gitlab.com/commercialhaskell/pipeline-base-image:34305074

stages:
  - build

variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"
    BASE_BRANCH: "master"
    OS_NAME: "linux"
    CACHE_S3_PREFIX: "stack"

build:
  stage: build
  only:
    - master
    - stable
  script: &build
    - export PATH=$HOME/.local/bin:$PATH
    - cache-s3 --prefix="${CACHE_S3_PREFIX}"
               --git-branch="${CI_BUILD_REF_NAME}"
               --suffix="${OS_NAME}"
               restore stack --base-branch="${BASE_BRANCH}";
      cache-s3 --prefix="${CACHE_S3_PREFIX}"
               --git-branch="${CI_BUILD_REF_NAME}"
               --suffix="${OS_NAME}"
               restore stack work --base-branch="${BASE_BRANCH}";
    - stack etc/scripts/release.hs check
    - if [ "${CI_BUILD_REF_NAME}" = "${BASE_BRANCH}" ]; then
        cache-s3 --prefix="${CACHE_S3_PREFIX}"
                 --git-branch="${CI_BUILD_REF_NAME}"
                 --suffix="${OS_NAME}"
                 save stack;
      fi;
      cache-s3 --prefix="${CACHE_S3_PREFIX}"
               --git-branch="${CI_BUILD_REF_NAME}"
               --suffix="${OS_NAME}"
               save stack work

manual_build:
  stage: build
  when: manual
  script: *build

docker_image_lts-11:
  stage: build
  when: manual
  script:
    - docker login -u "$PROD_DOCKER_USERNAME" -p "$PROD_DOCKER_PASSWORD"
    - etc/dockerfiles/stack-build/build.sh --push lts-11

docker_image_lts-12:
  stage: build
  when: manual
  script:
    - docker login -u "$PROD_DOCKER_USERNAME" -p "$PROD_DOCKER_PASSWORD"
    - etc/dockerfiles/stack-build/build.sh --push lts-12
