trigger: none
pr:
- master
- stable

schedules:
- cron: "0 0 * * *"
  displayName: Nightly build
  branches:
    include:
    - master
    - stable

variables:
  BASE_BRANCH: "master"
  CACHE_S3_PREFIX: "stack-nightly"
  CACHE_S3_VERSION: "v0.1.4"
  S3_BUCKET: "fpco-public-cache"
  AWS_REGION: "us-east-1"

jobs:
- template: ./.azure/azure-nightly-template-linux.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    os: linux
