resolver: lts-12.0

# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  packages:
    - zlib
    - unzip
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
extra-deps:
- hpack-0.29.0@rev:0
- githash-0.1.0.0@rev:0

ghc-options:
   "$locals": -fhide-source-paths
