resolver: snapshot.yaml

packages:
- .
- subs/pantry
- subs/curator

extra-deps:
# Ugly, temporary hack
- github: fpco/store
  commit: 8ff486ea5a16665c7fd279963344ac8ef99b6e2a
  subdirs:
  - store

# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  packages:
    - zlib
    - unzip
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true

ghc-options:
   "$locals": -fhide-source-paths
